config/routes.rb
Rails.application.routes.draw do
  resources :continents
  resources :languages
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root to: 'countries#index' # Página inicial
  #get 'countries/sobre'

  #get "/pages/:page" => "pages#sobre"
  get "/pages/:page" => "pages#show"
  get 'countries/listaContinentes'

  resources :countries
  
  root "pages#show", page: "sobre"
end

app/models/language.rb
class Language < ApplicationRecord
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  # GET /languages
  # GET /languages.json
  def index
    redirect_to root_path
    @languages = Language.all
  end

  # GET /languages/1
  # GET /languages/1.json
  def show
    redirect_to root_path
  end

  # GET /languages/new
  def new
    redirect_to root_path
    @language = Language.new
  end

  # GET /languages/1/edit
  def edit
    redirect_to root_path
  end

  # POST /languages
  # POST /languages.json
  def create
    @language = Language.new(language_params)

    respond_to do |format|
      if @language.save
        format.html { redirect_to @language, notice: 'Language was successfully created.' }
        format.json { render :show, status: :created, location: @language }
      else
        format.html { render :new }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /languages/1
  # PATCH/PUT /languages/1.json
  def update
    respond_to do |format|
      if @language.update(language_params)
        format.html { redirect_to @language, notice: 'Language was successfully updated.' }
        format.json { render :show, status: :ok, location: @language }
      else
        format.html { render :edit }
        format.json { render json: @language.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /languages/1
  # DELETE /languages/1.json
  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url, notice: 'Language was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_language
      @language = Language.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def language_params
      params.require(:language).permit(:nome)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_for(@language, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @language.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h4>

      <ul>
      <% @language.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/languages/edit.html.erb
<div class="page-header">
  <%= link_to languages_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @language, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing language</h1>
</div>

<%= render 'form' %>

app/views/languages/index.html.erb
<div class="page-header">
  <%= link_to new_language_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Language
  <% end %>
  <h1>Listing languages</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @languages) do |language| %>
            <td><%= language.nome %></td>
            <td><%= link_to 'Show', language %></td>
        <td><%= link_to 'Edit', edit_language_path(language) %></td>
        <td><%= link_to 'Destroy', language, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/languages/new.html.erb
<div class="page-header">
  <%= link_to languages_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New language</h1>
</div>

<%= render 'form' %>

app/views/languages/show.html.erb
<div class="page-header">
  <%= link_to languages_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_language_path(@language), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show language</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @language.nome %></dd>

</dl>