config/routes.rb
Rails.application.routes.draw do
  resources :continents
  resources :languages
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root to: 'countries#index' # Página inicial
  #get 'countries/sobre'

  #get "/pages/:page" => "pages#sobre"
  get "/pages/:page" => "pages#show"
  get 'countries/listaContinentes'

  resources :countries
  
  root "pages#show", page: "sobre"
end

app/models/continent.rb
class Continent < ApplicationRecord
end

app/controllers/continents_controller.rb
class ContinentsController < ApplicationController
  before_action :set_continent, only: [:show, :edit, :update, :destroy]

  # GET /continents
  # GET /continents.json
  def index
    # Foi adicionado
    redirect_to root_path
    @continents = Continent.all
  end

  # GET /continents/1
  # GET /continents/1.json
  def show
    # Foi adicionado
    redirect_to root_path
  end

  # GET /continents/new
  def new
    # Foi adicionado
    redirect_to root_path
    @continent = Continent.new
  end

  # GET /continents/1/edit
  def edit
    # Foi adicionado
    redirect_to root_path
  end

  # POST /continents
  # POST /continents.json
  def create
    @continent = Continent.new(continent_params)

    respond_to do |format|
      if @continent.save
        format.html { redirect_to @continent, notice: 'Continent was successfully created.' }
        format.json { render :show, status: :created, location: @continent }
      else
        format.html { render :new }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /continents/1
  # PATCH/PUT /continents/1.json
  def update
    respond_to do |format|
      if @continent.update(continent_params)
        format.html { redirect_to @continent, notice: 'Continent was successfully updated.' }
        format.json { render :show, status: :ok, location: @continent }
      else
        format.html { render :edit }
        format.json { render json: @continent.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /continents/1
  # DELETE /continents/1.json
  def destroy
    @continent.destroy
    respond_to do |format|
      format.html { redirect_to continents_url, notice: 'Continent was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_continent
      @continent = Continent.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def continent_params
      params.require(:continent).permit(:nome)
    end
end

app/helpers/continents_helper.rb
module ContinentsHelper
end

app/views/continents/_form.html.erb
<%= form_for(@continent, html: { class: "form-horizontal", role: "form" }) do |f| %>
  <% if @continent.errors.any? %>
    <div class="alert alert-danger alert-dismissable" role="alert">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
      <h4><%= pluralize(@continent.errors.count, "error") %> prohibited this continent from being saved:</h4>

      <ul>
      <% @continent.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome, class: "col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :nome, class: "form-control" %>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit class: "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/continents/edit.html.erb
<div class="page-header">
  <%= link_to continents_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to @continent, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-info-sign"></span>
    Show
  <% end %>
  <h1>Editing continent</h1>
</div>

<%= render 'form' %>

app/views/continents/index.html.erb
<div class="page-header">
  <%= link_to new_continent_path, class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-plus"></span>
    New Continent
  <% end %>
  <h1>Listing continents</h1>
</div>

<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <thead>
      <tr>
            <th>Nome</th>
            <th></th>
        <th></th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <%= content_tag_for(:tr, @continents) do |continent| %>
            <td><%= continent.nome %></td>
            <td><%= link_to 'Show', continent %></td>
        <td><%= link_to 'Edit', edit_continent_path(continent) %></td>
        <td><%= link_to 'Destroy', continent, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      <% end %>
    </tbody>
  </table>
</div>

app/views/continents/new.html.erb
<div class="page-header">
  <%= link_to continents_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <h1>New continent</h1>
</div>

<%= render 'form' %>

app/views/continents/show.html.erb
<div class="page-header">
  <%= link_to continents_path, class: 'btn btn-default' do %>
    <span class="glyphicon glyphicon-list-alt"></span>
    Back
  <% end %>
  <%= link_to edit_continent_path(@continent), class: 'btn btn-primary' do %>
    <span class="glyphicon glyphicon-pencil"></span>
    Edit
  <% end %>
  <h1>Show continent</h1>
</div>

<dl class="dl-horizontal">
  <dt>Nome:</dt>
  <dd><%= @continent.nome %></dd>

</dl>