config/routes.rb
Rails.application.routes.draw do
  resources :continents
  resources :languages
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #root to: 'countries#index' # Página inicial
  #get 'countries/sobre'

  #get "/pages/:page" => "pages#sobre"
  get "/pages/:page" => "pages#show"
  get 'countries/listaContinentes'

  resources :countries
  
  root "pages#show", page: "sobre"
end

app/models/country.rb
class Country < ApplicationRecord
	has_attached_file :imagem

	validates_attachment_content_type :imagem, 
	:less_than_or_equal_to => 10.megabytes,
	:content_type => ["image/png", "image/jpeg", "image/jpg", "image/gif", "image/mp4"],
	# add => avi, mpeg, e mp4
	:message => "Arquivos com no máximo 5MB"
end

app/controllers/countries_controller.rb
class CountriesController < ApplicationController
  before_action :set_country, only: [:show, :edit, :update, :destroy, :sobre]

  # GET /countries
  # GET /countries.json
  def index
    @countries = Country.all.paginate(:page => params[:page], :per_page => 20)
  end

  # GET /countries/1
  # GET /countries/1.json
  def show
  end

  # GET /countries/new
  def new
    redirect_to root_path
    @country = Country.new
  end

  # GET /countries/1/edit
  def edit
    # Foi adicionado
    redirect_to root_path
  end

  # POST /countries
  # POST /countries.json
  def create
    @country = Country.new(country_params)

    respond_to do |format|
      if @country.save
        format.html { redirect_to @country, notice: 'Country was successfully created.' }
        format.json { render :show, status: :created, location: @country }
      else
        format.html { render :new }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /countries/1
  # PATCH/PUT /countries/1.json
  def update
    respond_to do |format|
      if @country.update(country_params)
        format.html { redirect_to @country, notice: 'Country was successfully updated.' }
        format.json { render :show, status: :ok, location: @country }
      else
        format.html { render :edit }
        format.json { render json: @country.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /countries/1
  # DELETE /countries/1.json
  def destroy
    @country.destroy
    respond_to do |format|
      format.html { redirect_to countries_url, notice: 'Country was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sobre
  end

  def listaContinentes
    @countries = Country.all

    @valor = params[:escolha]
    if @valor.nil?
      @paises = Country.all.paginate(:page => params[:page], :per_page => 20)
      #flash[:warning] = "SEM EXCEÇÃO!"
    elsif @valor == 'america_do_sul'
      @paises = @countries.paginate(:page => params[:page], :per_page => 10).where("local = 'América do Sul'")
      flash[:warning] = "América do Sul!"
    elsif @valor == 'america_central'
      @paises = @countries.paginate(:page => params[:page], :per_page => 10).where("local = 'América Central'")
      flash[:warning] = "América Central!"
    elsif @valor == 'america_do_norte'
      @paises = @countries.paginate(:page => params[:page], :per_page => 10).where("local = 'América do Norte'")
      flash[:warning] = "América do Norte!"
    elsif @valor == 'europa'
      @paises = @countries.paginate(:page => params[:page], :per_page => 10).where("local = 'Europa'")
      flash[:warning] = "Europa!"
    elsif @valor == 'africa'
      @paises = @countries.paginate(:page => params[:page], :per_page => 10).where("local = 'África'")
      flash[:warning] = "África!"
    elsif @valor == 'asia'
      @paises = @countries.paginate(:page => params[:page], :per_page => 10).where("local = 'Ásia'")
      flash[:warning] = "Ásia!"
    elsif @valor == 'oceania'
      @paises = @countries.paginate(:page => params[:page], :per_page => 10).where("local = 'Oceania'")
      flash[:warning] = "Oceania!"
    else
      @paises = Country.all.paginate(:page => params[:page], :per_page => 20)
      #flash[:warning] = "FAIL!"
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_country
      @country = Country.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def country_params
      params.require(:country).permit(
        :nome, 
        :local, 
        :capital, 
        :extensao, 
        :idioma, 
        :populacao, 
        :pib, 
        :moeda, 
        :ano_referencia, 
        :imagem,
        :escolha
      )
    end
end

app/helpers/countries_helper.rb
module CountriesHelper
end

app/views/countries/_form.html.erb
<%= form_for(country,:html => { :multipart => true }) do |f| %>
  <% if country.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(country.errors.count, "error") %> prohibited this country from being saved:</h2>

      <ul>
      <% country.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <table align="center">
    <tr>
      <td>
        <div class="field">
          <%= f.label 'Imagem' %>
          <%= f.file_field :imagem %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="field">
          <%= f.label :local %>
          <%= f.text_field :local %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="field">
          <%= f.label :capital %>
          <%= f.text_field :capital %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="field">
          <%= f.label :extensao %>
          <%= f.number_field :extensao %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="field">
          <%= f.label :idioma %>
          <%= f.text_field :idioma %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="field">
          <%= f.label :populacao %>
          <%= f.number_field :populacao %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="field">
          <%= f.label :pib %>
          <%= f.text_field :pib %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="field">
          <%= f.label :moeda %>
          <%= f.text_field :moeda %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="field">
          <%= f.label :ano_referencia %>
          <%= f.number_field :ano_referencia %>
        </div>
      </td>
    </tr>

    <tr>
      <td>
        <div class="actions">
          <%= f.submit %>
        </div>
      </td>
    </tr>
  </table>    
<% end %>

app/views/countries/edit.html.erb
<h1>Editing Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Show', @country %> |
<%= link_to 'Back', countries_path %>

app/views/countries/index.html.erb
<p id="notice"><%= notice %></p>

<div id="titulo" class="animated pulse">
  Lista de Países
</div>

<div id="container">
  <table class="table table-condensed" align="center" width="80%">
    <thead>
      <tr>
        <th>ID</th>
        <th>País</th>
        <th>Capital</th>
        <th>Bandeira</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @countries.each do |country| %>
        <tr>
          <td><%= country.id %></td>
          <td><%= country.nome %></td>
          <td><%= country.capital %></td>
          <td><%= image_tag country.imagem.url, size:"100x60" %></td>
          <td><%= link_to 'Show', country %></td>
          <!-- <td><%# link_to 'Edit', edit_country_path(country) %></td> -->
          <!-- <td><%# link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br>

<center>
  <%= will_paginate @countries %>
</center>


<%# link_to 'Cadastrar País', new_country_path %>

app/views/countries/listaContinentes.html.erb
<div align="center">
	<h1> Continentes </h1>
</div>
<br>

<table align="center" width="50%" >
    
    <tr>
      <td>
	      <%= link_to controller: "countries", action: "listaContinentes", escolha: 'america_do_sul' do %>
	        <%= image_tag 'IMGS/america_do_sul_5.png', title: "América do Sul" %>
	        <%# "América do Sul" %>
	      <% end %>
      </td>

      <td>
	      <%= link_to controller: "countries", action: "listaContinentes", escolha: 'america_central' do %>
	        <%= image_tag 'IMGS/america_central_5.png', title: "América Central" %>
	        <%# "América Central" %>
	      <% end %>
      </td>

      <td>
	      <%= link_to controller: "countries", action: "listaContinentes", escolha: 'america_do_norte' do %>
	        <%= image_tag 'IMGS/america_do_norte_5.png', title: "América do Norte" %>
	        <%# "América do Norte" %>
	      <% end %>
      </td>

      <td>
	      <%= link_to controller: "countries", action: "listaContinentes", escolha: 'europa' do %>
	        <%= image_tag 'IMGS/europa_5.png', title: "Europa" %>
	        <%# "Europa" %>
	      <% end %>
      </td>

      <td>
	      <%= link_to controller: "countries", action: "listaContinentes", escolha: 'africa' do %>
	        <%= image_tag 'IMGS/africa_5.png', title: "África" %>
	        <%# "África" %>
	      <% end %>
      </td>

      <td>
	      <%= link_to controller: "countries", action: "listaContinentes", escolha: 'asia' do %>
	        <%= image_tag 'IMGS/asia_5.png', title: "Ásia" %>
	        <%# "Ásia" %>
	      <% end %>
      </td>

      <td>
	      <%= link_to controller: "countries", action: "listaContinentes", escolha: 'oceania' do %>
	        <%= image_tag 'IMGS/oceania_5.png', title: "Oceania" %>
	        <%# "Oceania" %>
	      <% end %>
      </td>

    </tr>

</table>

<br>

<div id="container">
  <table class="table table-condensed" align="center" width="80%">
    <thead>
      <tr>
        <th>ID</th>
        <th>País</th>
        <th>Capital</th>
        <th>Bandeira</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @paises.each do |country| %>
        <tr>
          <td><%= country.id %></td>
          <td><%= country.nome %></td>
          <td><%= country.capital %></td>
          <td><%= image_tag country.imagem.url, size:"100x60" %></td>
          <td><%= link_to 'Show', country %></td>
          <!-- <td><%# link_to 'Edit', edit_country_path(country) %></td> -->
          <!-- <td><%# link_to 'Destroy', country, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<center>
  <%= will_paginate @paises %>
</center>

app/views/countries/new.html.erb
<h1>New Country</h1>

<%= render 'form', country: @country %>

<%= link_to 'Back', countries_path %>

app/views/countries/show.html.erb
<p id="notice"><%= notice %>

<div id="titulo" class="animated pulse">
  Dados sobre <%= @country.nome %>
</div>

<center>
  <%= image_tag @country.imagem.url, size:"250x200" %>
</center>

<hr>

<table class="table" align="center">
  <tr>
    <th>ID:</th>
    <td><%= @country.id %></td>
  </tr>

  <tr>
    <th>Nome:</th>
    <td><%= @country.nome %></td>
  </tr>

  <tr>
    <th>Localização:</th>
    <td><%= @country.local %></td>
  </tr>

  <tr>
    <th>Capital:</th>
    <td><%= @country.capital %></td>
  </tr>

  <tr>
    <th>Extensao:</th>
    <td>
      <%= number_with_delimiter(@country.extensao, precision: 3, delimiter: ".") %> km²
    </td>
  </tr>

  <tr>
    <th>Idioma:</th>
    <td><%= @country.idioma %></td>
  </tr>

  <tr>
    <th>População:</th>
    <td><%= number_with_delimiter(@country.populacao, precision: 3, delimiter: ".") %> hab</td>
  </tr>

  <tr>
    <th>PIB:</th>
    <td><%= number_to_currency(@country.pib, precision: 2, unit: "US$ ", separator: ",", delimiter: ".") %></td> <!-- number_to_currency(1234567890.506, precision: 3) -->
  </tr>

  <tr>
    <th>Moeda:</th>
    <td><%= @country.moeda %></td>
  </tr>

  <tr>
    <th>Ano referência:</th>
    <td><%= @country.ano_referencia %></td>
  </tr>
</table>

<% descricao = @country.nome + ' é um país localizado na ' + @country.local + '. Sua capital é ' + @country.capital + '. Possui uma extensão de ' + @country.extensao.to_s + ' quilômetros quadrados. Sua população é estimada em ' + @country.populacao.to_s + ' de habitantes. ' + ' No país se fala o idioma ' + @country.idioma + '. A moeda utilizada é ' + @country.moeda
%>

<%# descricao = @country.nome + ' é um país localizado na ' + @country.local + '. Sua capital é ' + @country.capital + '. Possui uma extensão de ' %>


<%# link_to 'Edit', edit_country_path(@country) %>
<%# link_to 'Back', countries_path %>

<script type="text/javascript" src="responsivevoice.js"></script>

<div align="center">
<button class="butt js--triggerAnimation" onclick="responsiveVoice.speak('<%= descricao %>','Brazilian Portuguese Female', {rate: 0.9});" 
  type="image" value=""><%= image_tag ('IMGS/play.jpg') %></button>

<button class="butt js--triggerAnimation" onclick="responsiveVoice.pause();" type="button" value=""><%= image_tag ('IMGS/pause.jpg') %></button>

<button class="butt js--triggerAnimation" onclick="responsiveVoice.resume();" type="button" value=""><%= image_tag ('IMGS/continue.jpg')%></button>

<button class="butt js--triggerAnimation" onclick="responsiveVoice.cancel();" type="button" value=""><%= image_tag ('IMGS/stop.jpg') %></button>
</div>

app/views/countries/sobre.html.erb
<div id="titulo" class="animated pulse">
  Sobre o Paisesoft
</div>

<%= image_tag 'IMGS/america_do_sul_5.png', title: "América do Sul" %>

<p> O sistema está em fase Beta. </p>